const ItemTypes = {
    ITEM_TYPE_STRING: 'ITEM_TYPE_STRING',
    ITEM_TYPE_TEXT: 'ITEM_TYPE_TEXT',
    ITEM_TYPE_BOOL: 'ITEM_TYPE_BOOL',
    ITEM_TYPE_INT: 'ITEM_TYPE_INT',
    ITEM_TYPE_REAL: 'ITEM_TYPE_REAL',
    ITEM_TYPE_ITEM_TYPE_REF: 'ITEM_TYPE_ITEM_TYPE_REF',
    ITEM_TYPE_ITEM_REF: 'ITEM_TYPE_ITEM_REF',
    ITEM_TYPE_ITEMS_GROUP: 'ITEM_TYPE_ITEMS_GROUP',
}

export default ItemTypes;